blank_issues_enabled: false
contact_links:
  - name: Questions/discussion
    url: https://community.home-assistant.io/t/introducing-syslog-receiver-a-new-hacs-integration-for-ingesting-syslog-into-home-assistant
    about: Ask questions, discuss configuration, share your setup