name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Integration Folder
        run: |
          cd ${{ github.workspace }}/custom_components/syslog_receiver
          zip -r syslog_receiver.zip ./

      - name: Upload ZIP to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: custom_components/syslog_receiver/syslog_receiver.zip
          asset_name: syslog_receiver.zip
          tag: ${{ github.ref }}
          overwrite: true