name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version (strip 'v' if present)
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Set version in manifest.json
        run: |
          sed -i 's/"version": ".*"/"version": "${{ steps.version.outputs.version }}"/' \
            custom_components/syslog_receiver/manifest.json

      - name: ZIP Integration Folder
        run: |
          cd custom_components/syslog_receiver
          zip -r ../../syslog_receiver.zip ./

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          files: syslog_receiver.zip